GEMINI_API_KEY = "AIzaSyBUHZLlqoHJso6pqLbyQ5MeA403EoDOJYk"

[firebase_service_account]
type = "service_account"
project_id = "yatish-chatapp"
private_key_id = "1c171f961cafde28b65a37b5b7602c20b7521551"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdh03U1DA/vX/H
hFduT0ajiT09cu4T8p2+33HCyE0Lw3Y7Sp0yVCJOUZm+bquRkDqY8yy0CqQVKeGx
gCohskhGed0892DfleOHK6E/eNFiuX9aOEPLIdPDDJ6bej308f5qTbVFER0nPam8
A5ntCgwjvyGMeT68WMKqQgVFXupkNsfTsVa3mg0twejY4I4M5aeM4LchxhPLiABM
FGwVbsTHza+MeQUyuBCuaVfuMIE2GLnCVE/I+ewESDGPyVZ9wFiR6jOX6hxmgvxk
Oy1FZl6Znpc5MVnWaQzBvbI4hM82DrLoGfQXE+zM9ToQYOPTUSgf0bjpmWKpLyvD
lSaLwwc9AgMBAAECggEAA0FRwildUt/dVVfef6TLOqNiHNQ0Z7yedlyDKwl9EBZq
qch9rZXP/KrSgL0kNfaTQ2hY/uJuaBKMu6CAnmAi/rPTdshM2+nqwPcNlrRuLTpU
j550hizNha0L1P4mbBqZDYTMD2COZ+puCLjRVDTeMdnn/VFfEsDJyv9gwQF4WfhA
hHVo47/+WGsz81Jp5coczK/X3Cupu3c5Gia3x9FXbE4eo70Uc2I2PPZ6DTCM/Ouc
Z3Er/auBhpF8gVPxDAFtdlcZOtLoPKsoxafoz3QBReen265YWykojCX1twl7NIFZ
9RqywbM9W8opmviNpxVLL1LvNY5Hk/MOkQAz3CZKkQKBgQDPwan3DWXpSUB4a6Ve
/JQ58oyD7WOYGxa+WTgMuUtL9+SEJRY7O3TLMcvR0gjM5W6kocBN4T30o0H6kqsY
1iPKOTyh1A69osasUYjw3/yR82B0rXiitsjT9/KM+1i7rxNcpxHaFm3DMuHVTnAM
/1e9XDlfB4frp8jH2VgZ3/8lsQKBgQDCG8chcTtaTcnpTz9lRzsO1wd9ijO3Kdu3
7hMQShwmCNlxX5gPlbCzC+j+Qdkgft1YFSyqXWio3k38nLh4K8BiWGIJcEcbvM7l
ii3S2Korj87u1BVV0SBlJ0UNIzzCk2ZumcEA7WpehqYCe05vZnx2OcQzapm7xU8K
oe3ez48BTQKBgQCnF0ZAmXj+gFimwUT2uUPpuybCMFnqitbm7tDCgwCJL+2NTlqr
9uy/Q+R+c2N6j4hGRoVo3aA7slYtVmrfhdKxIQmfyfK1GEabbtQpjqwPImPQU3hz
vXiV6pQcSUabZHq5CPG1qlZLKRAyw2whN/h0JslJob/yizZTbX2LCfmmcQKBgHWR
u6Au5GNDAIwXGu/uIABSD9BjOAW2DcYvJk7UhI4pCANaglDWOuuHyDzQh4HeNZUX
ZjFeWHkIBTZ/emAXJ/SpUeAjqH5NcwenFTBDWXb/KLiRrsaG31dFXNajRDcabo2J
BVTZeHb+mWihZRWmfrZhMMxvwePwk3p+MASntRd1AoGAFbS0bWqQLAOoOnRh7yVJ
Cd5a5E0JoiQQ5bqo5eq2Q0oj8FV91uMLmCY+a9vTWzozbJInL5xX2u6mf0FZXLTh
Hr/oMjpydnG4Bg4Srak4CjKGiP6od1oINNXp0nWbCwC9PEUstEAcSXeqbZ+UCpU2
nOBXsZlpod4T9uNes3Q0fwQ=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@yatish-chatapp.iam.gserviceaccount.com"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40yatish-chatapp.iam.gserviceaccount.com"
